##############################
# Please edit this line to "not_sample_anymore" to make the bot run
is_example_config_or_not: "Ahhhh i will change this value to not_sample_anymore "
##############################
bot_token: "GET IT FROM otFather on telegram by creating new bot"
api_key: 'GET IT FORM my.telegram.org'
api_hash: 'GET IT FROM my.telegram.org'
owner_id: '810997061'
owner_username: 'HeManTSacHDevA'
message_dump: ""
gban_dump: ""
load: []
no_load: []
tz_number: ''
country: 'India'
strict_antispam: False
workers: 4
deepfry_token: None
del_cmds: False
sw_api: ''
cash_api_key: ''
time_api_key: ''
# Database
database_url: "postgres://username:password@host:5432/database_name"

# Permission
sudo_users: [810997061]
support_users: [810997061]
whitelist_users: [810997061]
